name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        run: |
          echo "Starting Jekyll build..."
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --trace
        env:
          JEKYLL_ENV: production

      - name: Check _site directory
        run: |
          echo "Checking _site directory..."
          ls -la _site || echo "_site directory not found!"
          du -sh _site || echo "_site is empty!"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site/*
          if-no-files-found: error

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/

      - name: Check downloaded _site directory
        run: |
          echo "Checking downloaded _site directory..."
          ls -la _site || echo "_site directory not found after download!"
          du -sh _site || echo "_site is empty after download!"

      - name: Deploy to GitHub Pages
        id: deployment
        if: success()
        uses: actions/deploy-pages@v2